// export enum LocationsActionTypes {}

export const GET_LOCATIONS_REQUEST = 'GET_LOCATIONS_REQUEST';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAIL = 'GET_LOCATIONS_FAIL';

// export const FETCH_LATEST_LOCATIONS_DATA_REQUEST = 'FETCH_LATEST_LOCATIONS_DATA_REQUEST';
// export const FETCH_LATEST_LOCATIONS_DATA_SUCCESS = 'FETCH_LATEST_LOCATIONS_DATA_SUCCESS';

export const SEARCH_LOCATION_REQUEST = 'SEARCH_LOCATION_REQUEST';
export const SEARCH_LOCATION_SUCCESS = 'SEARCH_LOCATION_SUCCESS';
export const SEARCH_LOCATION_FAIL = 'SEARCH_LOCATION_FAIL';
export const SEARCH_LOCATION_CANCEL = 'SEARCH_LOCATION_CANCEL';

export const ADD_LOCATION = 'ADD_LOCATION';
